spring.application.name=property-portfolio-api

# H2 Database configuration
spring.datasource.url=jdbc:h2:file: ./data/propertydb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

#Automatically create/update tables based on our @Entity classes
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

#Enable the H2 web console (lets view the database in a browser)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
